import { ChromaClient, Collection, IncludeEnum, Where } from "chromadb";

export class VectorService {
	private client: ChromaClient;
	private collections: Map<string, Collection> = new Map(); // Cache collections

	constructor() {
		// For a persistent local database, specify a path
		this.client = new ChromaClient();
		console.log("ChromaDB client initialized");
	}

	/**
	 * Gets or creates a ChromaDB collection.
	 * @param collectionName The name of the collection.
	 * @returns A promise that resolves to the Collection object.
	 */
	public async getOrCreateCollection(
		collectionName: string,
	): Promise<Collection> {
		if (this.collections.has(collectionName)) {
			return this.collections.get(collectionName)!;
		}

		console.log(`Getting or creating ChromaDB collection: ${collectionName}`);
		const collection = await this.client.getOrCreateCollection({
			name: collectionName,
			// You can define an embedding function here if not using a default one
			// For now, we assume embeddings are pre-generated by EmbeddingService
		});
		this.collections.set(collectionName, collection);
		console.log(`Collection '${collectionName}' ready.`);
		return collection;
	}

	/**
	 * Adds a document to a specified collection.
	 * @param collectionName The name of the collection.
	 * @param id A unique ID for the document.
	 * @param embedding The vector embedding of the document.
	 * @param document The original text document.
	 * @param metadata Optional metadata associated with the document.
	 * @returns A promise that resolves when the document is added.
	 */
	public async addDocument(
		collectionName: string,
		id: string,
		embedding: number[],
		document: string,
		// biome-ignore lint/suspicious/noExplicitAny: any
		metadata?: Record<string, string | number | boolean | any>,
	): Promise<void> {
		const collection = await this.getOrCreateCollection(collectionName);
		await collection.add({
			ids: [id],
			embeddings: [embedding],
			documents: [document],
			metadatas: [metadata || {}],
		});
		console.log(`Document '${id}' added to collection '${collectionName}'.`);
	}

	// biome-ignore lint/suspicious/noExplicitAny: any
	public async getDocument(collectionName: string, where: Where): Promise<any> {
		const collection = await this.getOrCreateCollection(collectionName);
		const results = await collection.get({
			where: where,
			include: [
				IncludeEnum.documents,
				IncludeEnum.metadatas,
				IncludeEnum.embeddings,
			],
		});
		return results;
	}

	/**
	 * Queries a collection for similar documents.
	 * @param collectionName The name of the collection.
	 * @param queryEmbeddings The embedding(s) to query with.
	 * @param nResults The number of results to return.
	 * @param where Optional filter for metadata.
	 * @param whereDocument Optional filter for document content.
	 * @returns A promise that resolves to the query results.
	 */
	public async queryCollection(
		collectionName: string,
		queryEmbeddings: number[],
		nResults: number,
		where?: Where,
		// biome-ignore lint/suspicious/noExplicitAny: any
	): Promise<any> {
		const collection = await this.getOrCreateCollection(collectionName);
		console.log(
			`Querying collection '${collectionName}' for ${nResults} results...`,
		);
		const results = await collection.query({
			queryEmbeddings: [queryEmbeddings],
			nResults: nResults,
			where: where,
			include: [
				IncludeEnum.documents,
				IncludeEnum.metadatas,
				IncludeEnum.distances,
			],
		});
		return results;
	}
}
